
stages:
  - build

services:
  - docker:dind

build:
  stage: build
  script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN 
    - docker build -t yape . 
    - sbt server/docker:publish
